### ISSUE TITLE
Change SerializeFn to not return input and written length

### ISSUE THREAD

**Issue by sdroege** [rust-bakery/cookie-factory#18]
Currently `SerializeFn` is always returning the input and the written length. With the change to work on everything that implements `Write`, this does not seem necessary anymore and complicates code more than needed.

- `Write` already keeps track of the current position and we pass a `&mut Write` around anyway, so there's no point in returning the current input
- For counting the written length, if actually needed, one could use the `Write` directly or we could add a convenience wrapper around any `Write` that simply counts how much was written and returns that value on request. As a side-effect this makes the `chain` combinator unneeded and allows to use `?` directly, and allows to *not* calculate the length if not needed. In addition to the plain `Write` wrapper, we could also have a `length()` function again that calculates the length.

@Keruspe @Geal Any opinions? I'd be happy to work on changing this if you agree.

**Comment by Keruspe** [comment]
I added the written length *specially* for the switch to write as it’s a
nice thing to provide and reimplementing length was clearly not trivial
with the API switch.
It’s easily chainable with the GenChain trait.
I’m fine with adding another trait on GenResult providing a « raw » method
or something like that just calling .0 on the tuple though

**Comment by sdroege** [comment]
> I added the written length *specially* for the switch to write as it’s a nice thing to provide and reimplementing length was clearly not trivial with the API switch.

Would you be fine with not always having the length if I implement a `length()` function like that one before on top of the current API? Unless I'm missing something this does not seem too difficult.

> It’s easily chainable with the GenChain trait.

Personally I'd prefer

```rust
string("a")(w)?;
string("b")(w)?;
```
over

```rust
string("a")(w)
    .chain(&string("b"))
```

It seems more Rusty and is less line-noise :) But the chaining is currently needed for calculating the sums of the lengths correctly (while this would be almost trivial to do if it was simply part of the `Write` that is used).

Do you have an opinion about returning the `Write` as part of the result?

**Comment by Keruspe** [comment]
Isn't the `Write` already returned?

Would this be acceptable?

```
string("a")(w).raw()?;
string("b")(w).raw()?;
```

I fail to see the point in hiding the length that the write call give us for free, and to add a length function that needs to recompute it

**Comment by sdroege** [comment]
> Isn't the `Write` already returned?

Yes, my point is that there's no point in returning it because keeping track of the state is already the job of the `Write` impl itself

> I fail to see the point in hiding the length that the write call give us for free

It's not for free and requires non-trivial calculations in combinators for updating the length. A calculation which would be much simpler if we let the `Write` take care of that if someone actually needs it (FWIW, I need it so I care about this working fine).

> and to add a length function that needs to recompute it

It would not have to be recomputed but would be computed as part of the writing just like now, but without having each combinator to worry about updating it correctly.

**Comment by sdroege** [comment]
For both points here, part of what I'm trying is to make it harder to make mistakes. Not having to calculate/update the length in each combinator is one thing, not having to chain the returned `Write` through everything needlessly is another.

**Comment by sdroege** [comment]
> Would this be acceptable?
> 
> ```
> string("a")(w).raw()?;
> string("b")(w).raw()?;
> ```

This also won't work inside combinators as you still need to update/calculate the length

**Comment by sdroege** [comment]
Basically for the length what I'm proposing is a

```rust
pub struct WriteCounter<W: Write>(W, usize);

impl<W: Write> WriteCounter<W> {
    pub fn new(w: W) -> Self {
        WriteCounter(w, 0)
    }

    pub fn position(&self) -> usize {
        self.1
    }
}

impl<W: Write> Write for WriteCounter<W> {
    fn write(&mut self, buf: &[u8]) -> Result<usize> {
        let written = self.0.write(buf)?;
        self.1 += written;
        Ok(written)
    }
}
```

`length()` or anything else could easily be implemented around that.

And that `GenResult` becomes, with the actual writer keeping track of what it has done so far (which it has to do anyway!):

```rust
type GenResult = Result<(), GenError>;
```

**Comment by sdroege** [comment]
I started implementing that to see if I'm missing something, and as a side-effect this will also get rid of the FIXME in the `hex` combinator easily as we don't have to guess the length anymore.

**Comment by Keruspe** [comment]
@sdroege can we close this now?

**Comment by sdroege** [comment]
Yes
