### ISSUE TITLE
Module hierarchy like in nom?

### ISSUE THREAD

**Issue by sdroege** [rust-bakery/cookie-factory#23]
Currently all types are directly at the top-level of the crate. It potentially makes sense to move them into various sub-modules similar to how it's done in nom.

As part of that, the compat `std::io` module could also be moved into a nicer place.

And maybe we could also move the macros out of the way into some kind of legacy module and mark them as deprecated :)

What do you think?

**Comment by Keruspe** [comment]
Something definitely needs to be done wrt this, yep

**Comment by Keruspe** [comment]
```
cookie_factory::{
    deprecated::macros::*, // meh, macros are always exported at the root of the crate no matter where they are defined but still...
    no_std::io::*,
}
```

**Comment by sdroege** [comment]
Yeah, sounds like a good start to me. I was also thinking about creating modules like nom's `branch`, `combinator`, `character`, `sequence`, etc. but those modules would look mostly empty right now so maybe not worth it.

**Comment by Geal** [comment]
yup, it's a good idea to have modules, better have them now and add stuff later, because changing module paths later will be a breaking change

**Comment by sdroege** [comment]
Ok, let's go with the top-level modules of nom then as a starting point, plus what @Keruspe said in the first comment above? I can prepare a PR for that if that sounds fine to everybody.

**Comment by sdroege** [comment]
This is fixed by https://github.com/rust-bakery/cookie-factory/commit/a265b1cd05e0e79678aca4bf679d6eaf9823e348 and follow-up commits now
