### ISSUE TITLE
Add a way to skip bytes in WriteCounter

### ISSUE THREAD

**Issue by Keruspe** [rust-bakery/cookie-factory#25]
With the recent removal of length from the GenResult, I face an issue:

I used to have this code:

```
/// Trait used to skip part of a buffer to later write inside the skipped part
pub trait SkipBuffer<'a> {
    /// Skip part of a buffer to later write inside the skipped part
    fn skip_buffer(self, offset: usize) -> (&'a mut [u8], Self);
}

impl<'a> SkipBuffer<'a> for &'a mut [u8] {
    fn skip_buffer(self, offset: usize) -> (&'a mut [u8], Self) {
        self.split_at_mut(offset)
    }
}

/// Apply a generator and serialize its length at the beginning of buffer
pub fn gen_with_len<'a, W: Write + SkipBuffer<'a>, F>(x: W, f: F) -> GenResult<W>
where
    F: Fn(W) -> GenResult<W>
{
    let (len_buf, x) = x.skip_buffer(4);
    let (x, len) = f(x)?;
    gen_long_uint(len_buf, len as LongUInt)?;
    Ok((x, len + 4))
}
```

Now, to get the length, I have to go through `WriteCounter`. Changing the signature of `F` from `W` to `WriteCounter<W>` *should* be enough, but then I need to implement `SkipBuffer` for `WriteCounter<W> where W: SkipBuffer`.

I currently see those solutions:
- add a constructor of `WriteCounter` that taked the `Write` and an `offset`
- change the `Skip` signature to return the skipped buffer too, and implement it for `WriteCounter<W> where W: Skip`
- merge `SkipBuffer` into cookie-factory

What do you think @Geal @sdroege ?

**Comment by sdroege** [comment]
On 12 July 2019 18:53:22 EEST, Marc-Antoine Perennou <notifications@github.com> wrote:
>
>Now, to get the length, I have to go through `WriteCounter`. Changing
>the signature of `F` from `W` to `WriteCounter<W>` *should* be enough,
>but then I need to implement `SkipBuffer` for `WriteCounter<W> where W:
>SkipBuffer`.

What is the problem with that?

>I currently see those solutions:
>- add a constructor of `WriteCounter` that taked the `Write` and an
>`offset`

How would that work? `Write` can't really write with an offset, skipping ahead.

You'd also need `Skip` here then. But how would that be used in your case?

>- change the `Skip` signature to return the skipped buffer too, and
>implement it for `WriteCounter<W> where W: Skip`

I think requiring `Skip` to return the skipped part will limit unnecessarily the types on which this can be implemented. You don't necessarily have access to previous data.

>- merge `SkipBuffer` into cookie-factory

I like the idea, it seems generally useful. I`d call it `SplitAt` or something, though. And it could come with a combinatorial similar to `skip` maybe?


I'll think about this a bit more and play around with your example on Sunday evening or Monday when I'm at a proper computer again :)


-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sdroege** [comment]
What I was thinking of is a combinator (not combinatorial! thanks autocorrect) like
```
fn split_at<W, R>(idx: usize, pre_write: F, post_write: G) -> SerializeFn<W>
  where
    G: Fn(W) -> GenResult<(W, R)>,
    F: Fn(W, R) -> GenResult<W>
```

And a trait basically allowing to perform that above action. `G` would be a serializing function that is called first for the part at/after the index and returns some value together with the writer, `F` would be a serializing function that is called second for the part before the index and gets the return value of `G` passed (and I guess many implementations of the trait would panic if `F` does not write the whole of the part before the index). And the whole thing is then returning the writer that is returned by `G` (i.e. at the position after `G` finished, after the block that `F` and `G` wrote).

This could be trivially implemented for byte slices for what you need, and could also be implemented for e.g. `Cursor<&mut [u8]>` (via `set_position() to jump temporarily backwards) or for any writer that also implements `Seek` (in the same way).

What do you think? Do I miss something? I didn't try implementing it yet :)

**Comment by Keruspe** [comment]
Looks nice indeed, not sure about the naming but that’s bikeshedding

**Comment by sdroege** [comment]
I'm bad at naming things, see `WriteCounter` :D If you have better suggestions, just say so.

**Comment by Keruspe** [comment]
I’m terrible too.

Maybe something inspired by the naming from nom such as preceded or whatnot

**Comment by Keruspe** [comment]
I’d probably fine with having just something like « write_at_pos or such
with a matching trait
