### ISSUE TITLE
Publish next release?

### ISSUE THREAD

**Issue by btrepp** [rust-bakery/cookie-factory#34]
Hi All,

I've been using this library, and it's fantastic. However I've noticed the no-std feature only works on the current code in git, not what's published on crates.io.

Is it possible to publish a release, or even pre-released version to crates.io?. That way I can depend on it in my crate.

It looks like there is a single commit added after the last publish that fixes the issue I am getting too 3adb3c3532fecbf5e1c3635a601f128219212f88

**Comment by Keruspe** [comment]
Will try and give it a look in the next days

**Comment by Keruspe** [comment]
0.3.2 is published
