### ISSUE TITLE
Serializing bits.

### ISSUE THREAD

**Issue by mmiecz** [rust-bakery/cookie-factory#35]
Hello,
I'm looking into a library that will be capable to serialize structs representing some specified protocol, and I've learned about cookie-factory, and it looks super interesting!
I have one question regarding usage of cookie-factory: I have a protocol that have numerous single bits flags (similar to TCP frame), and on the Rust side it is represented by struct with bools. What is the best way to serialize this into bytes? I couldn't find anything in documentation.
Thanks!

**Comment by Keruspe** [comment]
There could probably be something with https://crates.io/crates/bitvec
